# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 14c0e13abab132409a6aaf08144d4135758df983f7dd3e870c7c2fe58ba18427b871bf0a1187828db25bf0f8c4444063135ce28b599f457aa8ecb66ad6060110

test:
  secret_key_base: c4a7be3b638e0616bc3874394388e464cb16bebbc44d3cc4d71a50a6d4fa3cacdc396a3f98faafee33bc9f14c9d4c78454aec2b29307a07a84b4534791067753

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
